### ISSUE TITLE
Barrel (not only docker image) crashing when running with 1 cpu only

### ISSUE THREAD

**Issue by giowild** [barrel-db/barrel-docker#1]
Hi, just trying the docker image 0.8.0

An error is raised when the docker image is run with 1 vCPU. Tried both with Amazon t2.micro and t2.small (1 vCPU) and it crash. Tried with t2.medium, it works correctly instead.

This is docker log:
># sudo docker logs testbarrel
>Exec: /barrel/erts-8.1.1/bin/erlexec -noshell -noinput +Bd -boot /barrel/releases/0.8.0/barrel -mode >embedded -boot_var ERTS_LIB_DIR /barrel/lib -config /barrel/releases/0.8.0/sys.config -args_file >/barrel/releases/0.8.0/vm.args -pa -- foreground
>Root: /barrel
>/barrel
>10:58:00.480 [info] Application lager started on node barrel@0bb25de55462
>10:58:00.480 [info] Application cowboy started on node barrel@0bb25de55462
>10:58:00.481 [info] Application ssl_verify_fun started on node barrel@0bb25de55462
>10:58:00.481 [info] Application barrel_store started on node barrel@0bb25de55462
>10:58:00.482 [info] Application barrel_replicate started on node barrel@0bb25de55462
>10:58:00.483 [info] Application hackney started on node barrel@0bb25de55462
>enif_send: called from non-scheduler thread on non-SMP VM

**Comment by giowild** [comment]
Just built it from source too, and I get same error when using 1 cpu. Here the log:

=====
===== LOGGING STARTED Mon Feb 27 14:26:20 UTC 2017
=====
Exec: /home/ubuntu/barrel-platform/_build/prod/rel/barrel/erts-8.2/bin/erlexec -boot /home/ubuntu/barrel-platform/_build/prod/rel/barrel/releases/0.8.1/barrel -mode embedded -boot_var ERTS_LIB_DIR /home/ubuntu/barrel-platform/_build/prod/rel/barrel/lib -config /home/ubuntu/barrel-platform/_build/prod/rel/barrel/releases/0.8.1/sys.config -args_file /home/ubuntu/barrel-platform/_build/prod/rel/barrel/releases/0.8.1/vm.args -pa -- console
Root: /home/ubuntu/barrel-platform/_build/prod/rel/barrel
/home/ubuntu/barrel-platform/_build/prod/rel/barrel
Erlang/OTP 19 [erts-8.2] [source-fbd2db2] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

14:26:20.607 [info] Application lager started on node 'barrel@ip-172-31-18-235'
^M
14:26:20.607 [info] Application ssl_verify_fun started on node 'barrel@ip-172-31-18-235'^M
14:26:20.607 [info] Application ranch started on node 'barrel@ip-172-31-18-235'
^M
14:26:20.608 [info] Application barrel_store started on node 'barrel@ip-172-31-18-235'^M
14:26:20.609 [info] Application barrel_replicate started on node 'barrel@ip-172-31-18-235'^M
14:26:20.609 [info] Application cowboy started on node 'barrel@ip-172-31-18-235'^M
14:26:20.609 [info] Application hackney started on node 'barrel@ip-172-31-18-235'^M
Eshell V8.2  (abort with ^G)
(barrel@ip-172-31-18-235)1> enif_send: called from non-scheduler thread on non-SMP VM

**Comment by benoitc** [comment]
@giowild do you use the docker image with more than one core?

**Comment by giowild** [comment]
no 1 cpu 1 core, that is the number of cpu included in t2.micro and t2.small on amazon web services

**Comment by BernardNotarianni** [comment]
The `ERL_AFLAGS` environment variable with value  `"-smp enable"` should make it working.

Could you try setting it with the [`-e` option of docker](https://docs.docker.com/engine/reference/run/#/env-environment-variables)?

Maybe something like:

    $ docker run -e ERL_AFLAGS='-smp enable' --detach --name=test-barrel barrel/barrel

**Comment by BernardNotarianni** [comment]
@benoitc I am wondering if we should (or not) use this option by default. Thoughts?

http://erlang.org/pipermail/erlang-questions/2008-September/038231.html

**Comment by giowild** [comment]
>From OTP R12B the SMP version of the VM is automatically started as
default if the OS reports more than 1 CPU (or Core) and with the same
number of schedulers as CPU's or Cores.

Interesting, from this it seems that '-smp auto' should auto-determine how to start VM.. isn't it?

I will try to find a way to fix this and let you know

**Comment by giowild** [comment]
setting it as command line paraemeter in this way doesn't work..

> sudo docker run -e "ERL_AFLAGS='-smp enable'" --detach --name=testbarrel3 barrel/barrel

seems also that elixir makes things crash by not reading this value when it is specified via command line: https://snippets.aktagon.com/snippets/771-fixing-enif-send-env-null-on-non-smp-vmaborted-

It works correctly when putting it inside vm.args:

># Enable SMP on 1 CPU machines
>-smp enable

Tried all the values ('enable', 'disable' and 'auto') and checked that 'enable' is the only value which makes this work

**Comment by BernardNotarianni** [comment]
I think the best solution is indeed to put it in `vm.args`. 

I will create a new Docker image with `-smp enable` in `vm.args`.

**Comment by BernardNotarianni** [comment]
@giowild just pushed a new docker image to https://hub.docker.com/r/barrel/barrel/ with tag 0.8.2

Might worth to give it a try.

**Comment by giowild** [comment]
@BernardNotarianni  yesss! the *latest* tag is now working well with 1 cpu too
